version: '3.8'

services:
  stream-monitor:
    build: .
    command:
      - -api-server
      - ${API_SERVER}
      - -api-token
      - ${API_TOKEN}
      - -stream-duration
      - 30s
      - -bind
      - "0.0.0.0:9090"
      - -v
      - "10"
    entrypoint:
      - /root/stream-monitor
    ports:
      - "9090:9090"

  # useful for interacting with the build context
  builder:
    build:
      context: .
      target: builder
    command: ash
    ports:
      - "9091:9090"
    volumes:
      - ./:/root
