name: Record Tester Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Registry
      env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag livepeer/streamtester:$(date +%s)
      run: docker build . --file Dockerfile.record-tester --tag livepeer/streamtester:record-tester --build-arg version=$(git describe --dirty)
    - name: Get tag name
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Tag version
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        docker tag livepeer/streamtester:record-tester livepeer/streamtester:record-tester${{ steps.get_version.outputs.VERSION }}
        docker push livepeer/streamtester:record-tester${{ steps.get_version.outputs.VERSION }}
    - name: Describe
      id: describe
      run: |
        VER=$(git describe)
        echo "version_from_git=$VER" >> $GITHUB_ENV
    - name: Push Docker Container to Registry
      run: |
        docker tag livepeer/streamtester:record-tester livepeer/streamtester:record-tester-${{ env.version_from_git }}
        docker push livepeer/streamtester:record-tester
